### ISSUE TITLE
Failed to retrieve certificate from CA

### ISSUE THREAD

**Issue by magtimmermans** [aloopkin/WinCertes#49]
**Describe the bug**
When updating a certificate it says: "Failed to retrieve certificate from CA: Can not find issuer 'C=US,O=Internet Security Research Group,CN=ISRG Root X1' for certificate 'C=US,O=Let's Encrypt,CN=R3'."

**Expected behavior**
A renewed certificate

**Screenshots or Logs**
PS C:\Program Files\WinCertes> .\WinCertes.exe -d www.speedcams.eu -d speedcams.eu -p -b "xxxxx" --show
Service URI:    https://acme-v02.api.letsencrypt.org/directory
Account Email:  xxxxxxxxxxxxxxxxxxxxxxxxxxxx
Registered:     yes
Auth. Mode:     http-01 validation standalone
HTTP Port:      80
IIS Bind Name:  xxxxx
Import in CSP:  yes
PS Script File: none
Renewal Delay:  30 days
Task Scheduled: yes
Cert Enrolled:  yes

**Desktop (please complete the following information):**
 - OS: Windows Server
 - Version 2016

**Comment by aloopkin** [comment]
Hello,

You should probably manually import ISRG Root X1 into the trusted CAs using certmgr.msc

ISRG Root X1 certificate can be downloaded from there:
https://letsencrypt.org/certificates/

**Comment by magtimmermans** [comment]
Thanks. I will try this.

**Comment by webprofusion-chrisc** [comment]
Ax @aloopkin suggests the root cause of this issue is that the Certes library requires a known root and in your case you don't have that one installed. By default windows servers will acquire root certificates automatically but you either have Windows Updates blocked or a group policy configuration that has switched of CA root cert updates (this is common because there was a windows bug years ago and in response a lot of domain admins turned off CA root updates and never switched it back on, but roots do expire eventually). 

The reason you're seeing this now is that LE accidentally switched on the shorter certificate chain by default (which terminates at ISRG Root X1) and they have now reverted this, so your request would now work.

Your issue is the same as: https://community.letsencrypt.org/t/certificate-renewal-error/208244/14

**Comment by magtimmermans** [comment]
Thank you. It is solved.

**Comment by webprofusion-chrisc** [comment]
If anyone coming from the future and find this issue, from 2024-02-08 Let's Encrypt will no longer offer their old certificate chain ending in DST Root CA X3 by default https://community.letsencrypt.org/t/shortening-the-lets-encrypt-chain-of-trust/201580

If your system does not know ISRG Root X1 (self-signed) as a Trusted Certification Authority in the Local Machine certificate store you will need to add it, or better yet turn on windows updates and automatic CA root updates.

**Comment by nasrullonurullaev** [comment]
![Screenshot 2024-02-24 232411](https://github.com/aloopkin/WinCertes/assets/61620246/09253a78-0324-43f4-89c9-a7aada752c4d)


> If anyone coming from the future and find this issue, from 2024-02-08 Let's Encrypt will no longer offer their old certificate chain ending in DST Root CA X3 by default https://community.letsencrypt.org/t/shortening-the-lets-encrypt-chain-of-trust/201580
> 
> If your system does not know ISRG Root X1 (self-signed) as a Trusted Certification Authority in the Local Machine certificate store you will need to add it, or better yet turn on windows updates and automatic CA root updates.

In my system, I have ISRG Root X1 (see attached image), but I still encounter the following error when generating an SSL certificate using wincertes.exe:

Command: WinCertes.exe -e support@example.com -p -b "EXAMPLE Server" -d example.com

Output: Failed to retrieve certificate from CA: Can not find issuer 'C=US,O=Internet Security Research Group,CN=ISRG Root X1' for certificate 'C=US,O=Let's Encrypt,CN=R3'.

**Comment by webprofusion-chrisc** [comment]
My comment on the Let's Encrypt forum forgot to include the caveat that you also need to load the issuers from the machine cert store for it to be automatically picked up (mentioned later).

The workaround if you are not loading roots from the windows store is to use the latest version of the Certes library (3.x) which was released a few years ago and includes an embedded ISRG Root X1 used when building the PFX. Alternatively there are other clients such as my own https://certifytheweb.com which now don't require known roots for PFX builds.

**Comment by nasrullonurullaev** [comment]
> My comment on the Let's Encrypt forum forgot to include the caveat that you also need to load the issuers from the machine cert store for it to be automatically picked up (mentioned later).
> 
> The workaround if you are not loading roots from the windows store is to use the latest version of the Certes library (3.x) which was released a few years ago and includes an embedded ISRG Root X1 used when building the PFX. Alternatively there are other clients such as my own https://certifytheweb.com which now don't require known roots for PFX builds.

Sorry, if I understood correctly, there is no way to get certificates using wincertes.exe here, is there?

**Comment by webprofusion-chrisc** [comment]
@nasrullonurullaev I'm not sure, the app does appear to load the issuers from the machine certificate store.: https://github.com/aloopkin/WinCertes/blob/9fc0f2cfc49d77290f4be69ad8819dba43ddc101/WinCertes/CertesWrapper.cs#L380

Check that your machine is receiving windows updates and that CA Root auto update is working and enabled. For a normal windows machine with no restrictions applied you would normally only have to visit a site (in IE or powershell) using a given root cert for the associated intermediates and root to be auto imported. Years ago some administrators added blocks to CA auto updates into group policy because of a temporary windows update bug and many machine are still affected by this because they left it switched off (across all of group policy), so as root certificates expire these machines will stop being able to access https resources.
